### PR TITLE
Fix: Recursive  fetch on getAllWithCoordinates 

### PR DESCRIPTION
**Pull request by delemaf**
use default app namespace### :pushpin: References

-   **Issue:** [Closes](https://app.clickup.com/t/86957kfzj) #86957kfzj

### CODE REVIEW

**Comment by ifoche** [comment]
Task linked: [CU-86957kfzj Filter out OU before asking for all points in "import rule"](https://app.clickup.com/t/86957kfzj)

**Comment by MiquelAdell** [comment]
Hi @delemaf sorry I did not get to review that… but how is it that you are closing it? Thanks!

**Comment by delemaf** [comment]
Hi @MiquelAdell, I close it because it wasn't the proper solution, the right PR is this one https://github.com/EyeSeeTea/dhis2-gee-app/pull/54

**Comment by MiquelAdell** [comment]
great @delemaf thanks!

**Pull request closed without merging**
