### PR TITLE
Update to gee 0.1.232

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References

-   **Issue:** Closes https://app.clubhouse.io/eyeseetea/story/247/upgrade-google-earth-engine-library-to-v0-1-232

### :memo: Implementation

- I have updated to 0.1.232, test it, and works

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
screenshots_1601832409_1926_04102020_945x589

@xurxodev Any thoughts on why this could be happening?

**Comment by ifoche** [comment]
BTW yarn ask me to do a yarn upgrade, but if I do I get immediately compilation errors...

**Comment by xurxodev** [comment]
@ifoche fixed the empty gee dataset selector dialog. This bug was because has changed the model in the https://earthengine-stac.storage.googleapis.com/catalog/catalog.json. For every dataset, for example, https://earthengine-stac.storage.googleapis.com/catalog/AAFC_ACI.json gee:type was under properties prop and now directly under the root.

**Comment by xurxodev** [comment]
@ifoche About yarn dependencies, the warning seems an outdated dependency problem with Browserslist: caniuse-lite, but run yarn upgrade update all dependencies, and seems there are conflicts between dependencies. caniuse-lite is a related dependency from other dependencies, I think to try to solve this may not be easy, and dangerous at this moment to release a new version. I think we should create an issue for the next release. Alexis has told me this warning is not a problem.

**Review by ifoche — APPROVED** [review]
thanks @xurxodev and @tokland

**Pull request merged**
